# Generated by Django 2.1.4 on 2018-12-12 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainupload', '0003_auto_20181209_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded',
            field=models.TimeField(default=datetime.datetime(2018, 12, 12, 9, 2, 13, 186174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=mainupload.models.content_file_name),
        ),
    ]
