# Generated by Django 2.1.4 on 2018-12-12 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainupload', '0004_auto_20181212_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded',
            field=models.TimeField(default=datetime.datetime(2018, 12, 12, 9, 2, 23, 645580, tzinfo=utc)),
        ),
    ]
