# Generated by Django 2.1.4 on 2018-12-12 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainupload', '0005_auto_20181212_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
