# Generated by Django 2.1.2 on 2018-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
